menu:
  Home: /
  Archives: /archives
  Resume: /resume.html

excerpt_link: read more

mathjax: true
fancybox: true

social:
  twitter: true
  github: true
  rss: true

twitter:
  username: ahdinosaur

github:
  username: ahdinosaur

addit:
  facebook: false
  twitter: true
  gplus: true
  pinit: false
  publid:
